server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST:localhost}:5432/Auth_db
    username: postgres
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: nadia.arrahime@gmail.com
    password: bxew adnw injk hugm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 816176180071-0e0pq756du7pbelhef8ue6ilu9ec26l6.apps.googleusercontent.com # Hiding the real ID
            client-secret: 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 # Hiding the real Secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
jwt:
  secret: unistage_secret_unistage_secret_123456