# 1. Port & Application Name
server.port=8085
spring.application.name=notification-service
# 2. Eureka Registration
# Use the EUREKA_HOST variable or default to eureka-server
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:eureka-server}:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true
# 3. Kafka Consumer Config
spring.kafka.consumer.bootstrap-servers=${KAFKA_HOST:kafka}:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
# Bach Kafka yfhem l'format dyal l'messages
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 4. MongoDB Config
spring.data.mongodb.uri=mongodb://${MONGO_HOST:mongodb}:27017/unistage_notifications
# 5. Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nadia.arrahime@gmail.com
# App Password (bla espaces)
spring.mail.password=bxewadnwinjkhugm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true