spring.application.name=internship-service
server.port=8083

# --- POSTGRESQL CONFIG ---
spring.datasource.url=jdbc:postgresql://postgres:5432/internship_db
# Add these two lines here:
spring.datasource.username=postgres
spring.datasource.password=1234  # <-- Change '1234' to whatever your actual database password is!

# --- EUREKA CONFIG ---
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=0
