spring.application.name=internship-service
server.port=8083

# --- POSTGRESQL CONFIG (Docker Network) ---
# Changed 'localhost' to 'postgres' (the name of your DB service)
spring.datasource.url=jdbc:postgresql://postgres:5432/internship_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Set the dialect explicitly to help Hibernate find it immediately
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- KAFKA CONFIG ---
# Changed 'localhost' to 'unistage-kafka' (check your compose service name for Kafka)
spring.kafka.bootstrap-servers=unistage-kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Zidi had l-ligne bach mat-tra lik hta error f l-format dial l-JSON
spring.kafka.producer.properties.spring.json.trusted.packages=*

# --- EUREKA CONFIG ---
# 1. Use the service name 'eureka-server'
# 2. MUST set register and fetch to TRUE so it shows up in the dashboard
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# This helps the service use the container name instead of a random ID in Eureka
eureka.instance.hostname=internship-service
eureka.instance.prefer-ip-address=true
